include:
  - frontend/docker-compose.dev.yml
  - backend/docker-compose.dev.yml

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-dev
    depends_on:
      - app
      - server