version: '3.8'

services:
  server:
    image: chat-app-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    container_name: chat-app-backend-dev
    environment:
      PORT: 3001
      CHOKIDAR_USEPOLLING: "true"