services:
  server:
    image: chat-app-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./src:/usr/src/app/src
      - ./.eslintignore:/usr/src/app/.eslintignore
      - ./.eslintrc:/usr/src/app/.eslintrc
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./.env:/usr/src/app/.env
    container_name: chat-app-backend-dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - redis-dev
    env_file:
      - .env
  redis-dev:
    image: redis
    restart: always
    ports:
      - 6379:6379
    command: ['redis-server', '/usr/local/etc/redis/redis.conf', '--appendonly', 'yes'] # Overwrite the CMD
    volumes: # Declare the volume
      - ./redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf