name: Backend - Test with Jest

on:
  pull_request:
    branches: [ "main" ]
    paths: ["backend/**"]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'backend'
    strategy:
      matrix:
        node-version: [20.x]
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }} for backend
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Create .env file
      env:
        TEST_ENV_FILE: ${{ secrets.BACKEND_TEST_ENV }}
      run: echo $TEST_ENV_FILE | base64 --decode > .env.test.local
    - uses: supabase/setup-cli@v1
      with:
        version: latest
    - run: supabase start
    - name: Install backend dependencies
      run: npm i --legacy-peer-deps
    - name: Test backend
      run: npm run test