name: Push Image to Docker and Deploy to Render

on:
  push:
    branches:
      - main
      - CD-Test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}-frontend:latest
      -
        name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}-backend:latest
      - name: Render deployment for frontend
        run: curl https://api.render.com/deploy/${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}&imgURL=${{ secrets.RENDER_FRONTEND_IMAGE_URL }}
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')}}
      - name: Render deployment for backend
        run: curl https://api.render.com/deploy/${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}&imgURL=${{ secrets.RENDER_BACKEND_IMAGE_URL }}
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')}}
