name: Push Image to Docker and Deploy to Render

on:
  push:
    branches:
      - main
      - CD-Test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Render deployment for frontend
        run: curl https://api.render.com/deploy/${{ secrets.FRONTEND_RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')}}
