name: Push Image to Docker and Deploy to Render

on:
  push:
    branches:
      - main
      - CD-Test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}-backend:latest
      - name: Render deployment for backend
        run: curl https://api.render.com/deploy/srv-${{ secrets.BACKEND_RENDER_SERVICE_ID }}?key=${{ secrets.BACKEND_RENDER_KEY }}&imgURL=${{ secrets.RENDER_BACKEND_IMAGE_URL }}
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')}}
      - name: Render deployment for frontend
        run: curl https://api.render.com/deploy/srv-${{ secrets.FRONTEND_RENDER_SERVICE_ID }}?key=${{ secrets.FRONTEND_RENDER_KEY }}
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')}}
