name: Frontend - Deploy to Render

on:
    push:
        branches:
            - main
            - CD-Test
        paths: ["frontend/**"]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Render deployment for frontend
              run: curl https://api.render.com/deploy/srv-${{ secrets.FRONTEND_RENDER_SERVICE_ID }}?key=${{ secrets.FRONTEND_RENDER_KEY }}
              if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')}}
